export const TERMS = Object.freeze({
  fold: ['弃牌', 'Fold'],
  check: ['过牌', 'Check'],
  call: ['跟注', 'Call'],
  bet: ['下注', 'Bet'],
  raise: ['加注', 'Raise'],
  allIn: ['全下', 'All-in'],
  pot: ['底池', 'Pot'],
  flop: ['翻牌', 'Flop'],
  turn: ['转牌', 'Turn'],
  river: ['河牌', 'River'],
  showdown: ['摊牌', 'Showdown'],
  dealer: ['庄家', 'Dealer / D'],
  sb: ['小盲', 'Small Blind / SB'],
  bb: ['大盲', 'Big Blind / BB'],
  preflop: ['翻牌前', 'Preflop'],
  headsUp: ['单挑', 'Heads-up'],
  kicker: ['踢脚', 'Kicker'],
  splitPot: ['平分底池', 'Split pot'],
  sidePot: ['边池', 'Side pot'],
  hand: ['牌局', 'Hand'],
  match: ['对局', 'Match'],
});
